# Auto-generated by scripts/harden_build_attest.py; do not edit manually.
# Generated at 2025-10-13T11:48:33.612609+00:00
EXPECTED_SELF_SHA256 = {
    "attest.cpython-310-darwin.so": "a300aff3f3d17c909988bbc92f8a678657f28681b3b1534cea04fccf3f1b7606",
    "attest.cpython-310-x86_64-linux-gnu.so": "50c5425eca5ec7a6340688700c0b3d445aade289217624828e12c3d4ab425db8",
}
