# Auto-generated by scripts/harden_build_attest.py; do not edit manually.
# Generated at 2025-11-03T14:29:15.394799+00:00
EXPECTED_SELF_SHA256 = {
    "attest.cpython-310-darwin.so": "2ebd9c8da5c399839c778d75d74dc537e8f7c7236d6371a3f5f8dde2f47f6341",
    "attest.cpython-310-x86_64-linux-gnu.so": "73f3ddf4e70a4c8dd9884ae2df666fec3163cb3c7afa25f85a485e2b66c067d2",
}
